command:
  - "streamlit"
  - "run"
  - "app/app.py"
  - "--server.port"
  - "8000"
  - "--server.address"
  - "0.0.0.0"
  - "--server.headless"
  - "true"

env:
  - name: "DATABRICKS_HTTP_PATH"
    value: "/sql/1.0/warehouses/bb6574c313ec0c4f"
  - name: "UC_CATALOG"
    value: "hackathon"
  - name: "UC_SCHEMA"
    value: "trust_desk"
  - name: "LLM_ENDPOINT"
    value: "databricks-meta-llama-3-3-70b-instruct"
  - name: "LAKEBASE_HOST"
    value: "ep-solitary-shape-d8czihec.database.us-east-2.cloud.databricks.com"
  - name: "LAKEBASE_DB"
    value: "databricks_postgres"
  - name: "LAKEBASE_USER"
    value: "freeformelm@gmail.com"
  - name: "LAKEBASE_INSTANCE_NAME"
    value: "ep-solitary-shape-d8czihec"
