command:
  - "streamlit"
  - "run"
  - "app.py"
  - "--server.port"
  - "8000"
  - "--server.address"
  - "0.0.0.0"

env:
  - name: "DATABRICKS_HTTP_PATH"
    value: "/sql/1.0/warehouses/bb6574c313ec0c4f"
  - name: "UC_CATALOG"
    value: "hackathon"
  - name: "UC_SCHEMA"
    value: "trust_desk"
  - name: "LLM_ENDPOINT"
    value: "databricks-meta-llama-3-3-70b-instruct"
  - name: "LAKEBASE_HOST"
    valueFrom: "lakebase_host"
  - name: "LAKEBASE_DB"
    valueFrom: "lakebase_db"
  - name: "LAKEBASE_USER"
    valueFrom: "lakebase_user"
  - name: "LAKEBASE_PASSWORD"
    valueFrom: "lakebase_password"
